from sqlalchemy.types import Integer, VARCHAR, SmallInteger


SCHEMAS = {
    "players": {
        "pid": Integer,
        "fname": VARCHAR(length=25),
        "lname": VARCHAR(length=25),
        "yrsplayed": SmallInteger,
        "jerseynum": SmallInteger,
        "pos": VARCHAR(length=14),
        "status": VARCHAR(length=8),
        "tid": Integer,
        "goatflag": VARCHAR(length=1),
    },
    "teams": {
        "id": Integer,
        "full_name": VARCHAR(length=22),
        "abbreviation": VARCHAR(length=3),
        "nickname": VARCHAR(length=13),
        "city": VARCHAR(length=13),
        "state": VARCHAR(length=20),
        "year_founded": SmallInteger,
    },
    "matchups": {
        "gid": Integer,
        "sznstr": VARCHAR(length=7),
        "date": VARCHAR(length=10),
        "htid": Integer,
        "atid": Integer,
        "nquarters": SmallInteger,
        "matchupstr": VARCHAR(length=9),
        "HPTS": SmallInteger,
        "APTS": SmallInteger,
    },
    "plays": {
        "playid": Integer,
        "pid": Integer,
        "gid": Integer,
        "type": VARCHAR(length=4),
        "description": VARCHAR(length=90),
        "url": VARCHAR(length=120),
        "tid": Integer,
        "hscore": VARCHAR(length=9),
        "ascore": VARCHAR(length=9),
        "time": VARCHAR(length=5),
        "quarter": SmallInteger,
    },
}

PANDAS_SCHEMA = {
    "matchups": {
        "gid": int,
        "sznstr": str,
        "date": str,
        "htid": int,
        "atid": int,
        "nquarters": int,
        "matchupstr": str,
        "HPTS": int,
        "APTS": int,
    },
    "teams": {
        "id": int,
        "full_name": str,
        "abbreviation": str,
        "nickname": str,
        "city": str,
        "state": str,
        "year_founded": int,
    },
    "plays": {
        "playid": int,
        "pid": int,
        "gid": int,
        "type": str,
        "description": str,
        "url": str,
        "tid": "Int64",
        "hscore": str,
        "ascore": str,
        "time": str,
        "quarter": int,
    },
    "players": {
        "pid": int,
        "fname": str,
        "lname": str,
        "yrsplayed": int,
        "jerseynum": "Int64",
        "status": str,
        "tid": int,
        "pos": str,
        "goatflag": str,
    },
}
